### ISSUE TITLE
Project aborted?

### ISSUE THREAD

**Issue by ZeGregg** [stipsan/uikit-react#6]
Hi,

Did you abort the project? 

Regards

**Comment by stipsan** [comment]
Hey @ZeGregg,

It's not aborted, but it's a valid question considering there's been zero activity for many months.

When I set out to start this project it was to cover a need. There were a lot of great ui libraries for React but I couldn't find any that was as solid as UIkit.
I quickly discovered I had a lot to learn, it was my first npm package, first time using Jest and TravisCI, etc.
After I begun coding various components I realized that there not only were a lot of projects I needed to get familiar with, like webpack, react-router and more importantly a lot of react ui projects started to take a stand wether to go with inline styles, css/less/sass or something else.
I decided that I needed to learn a lot before I could take this project further.

I do plan on revisiting it soon, and breathe new life into it.

If you have a shared interest I'd love to add you to this repo so we can work on it together. Or we can move this repo to an organization so that it's not controlled by my github account but by contributors.
I just want to see this happen. UIkit is awesome, but its dependency on jQuery ruins it for many of us.

**Comment by ZeGregg** [comment]
@stipsan sorry for the delay. Unfortunately I have not enough skills to help you in this project. I know very well UIKit but I am noob in React

**Comment by samueljseay** [comment]
Hi, I'd be really interested in contributing to this effort. I agree UIKit is one of the nicest out there.

Do you have a roadmap of what you'd want to implement first? I assume from your comment you plan to implement the JQuery plugin functionality in React?

**Comment by stipsan** [comment]
@ZeGregg that's ok :)

@samueljseay ok I'll add you!

Yes, the goal is to drop the jQuery requirement when using UIkit first and foremost. 
So that you can easily use UIkit with React.

**Comment by stipsan** [comment]
I'm returning to this now. I'll setup a milestone with issues on what's going to happen next 😄
